#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://install.appcenter.ms/orgs/cdmc/apps/plasticoin-ios/distribution_groups/public                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://install.appcenter.ms/orgs/cdmc/apps/plasticoin/distribution_groups/public                                         # Enter Google Play Store URL.
presskit_download_link                    : https://opencircular.github.io/docs/                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Plasticoin                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : ♻️ Get rewarded for recycling <br/> 🔄 Stimulate a circular Plastics Economy

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Nick                                
your_link                                 : https://opencircular.github.io/docs/                   
your_city                                 : World                                
email_address                             : plasticoinapp@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : plasticoinapp
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Schedule Pickup
    description                           : Schedule a collection pickup at the convenience of your home with the app
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : Locate Drop Off
    description                           : Locate a drop center near you and earn a reward
    fontawesome_icon_name                 : compass

  - title                                 : Wallet
    description                           : Track rewards and points in your wallet
    fontawesome_icon_name                 : wallet

  - title                                 : Rewards
    description                           : Choose from cell phone minutes to local discounts
    fontawesome_icon_name                 : dollar-sign

  - title                                 : Become a Collector
    description                           : Earn cash while protecting the environment
    fontawesome_icon_name                 : car
  
  - title                                 : Run a drop center
    description                           : Own a building or land? Earn cash running a drop center to aggregate recyclables
    fontawesome_icon_name                 : store-alt

  - title                                 : Route Builder
    description                           : Build an efficent route to pickup recycling
    fontawesome_icon_name                 : route

  - title                                 : Smart Route
    description                           : Automatically build a smart route and assign collectors in your region.
    fontawesome_icon_name                 : map-marked-alt

  - title                                 : Data API
    description                           : Sign up to access analytics about the flow of material in your region!
    fontawesome_icon_name                 : database

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.3
topbar_title_color                        : "#ffffff"

cover_image                               : assets/screenshotcrush.jpg #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
